### ISSUE TITLE
Problem with return stream

### ISSUE THREAD

**Issue by superRandomGuy941** [MrAyianaLex/streamdeck-steelseries-sonar#2]
Hi, I just tried out this plugin and found this red lock on the 'return stream' thing over it. Is this supposed to be there or how do I get it away?

![image](https://github.com/MrAyianaLex/streamdeck-steelseries-sonar/assets/133808080/6a79642c-8b71-482c-8ed9-0355305f2413)

**Comment by MrAyianaLex** [comment]
Hello,
Actions related to streamer mode appear to lock if streamer mode is not activated.
If you change the mode manually from Sonar, you must delete and return the button to force its update.

**Comment by superRandomGuy941** [comment]
I deleted the button 3 times and set it up again, however it does nothing although streamer mode is active.

![image](https://github.com/MrAyianaLex/streamdeck-steelseries-sonar/assets/133808080/1190320b-22a4-4726-87b7-7d91167b6504)

**Comment by MrAyianaLex** [comment]
i need "%appdata%\Elgato\StreamDeck\Plugins\com.mrayianalex.sonar.sdPlugin\pluginlog.log" file to see if there are any planting indications.
